### ISSUE TITLE
Add a query param for page size on the feed 

### ISSUE THREAD

**Issue by cristidrg** [Comic-Con-Museum/fan-forge-backend#49]
# Goal
This would let us query for 40 items on desktop and 10 items on mobile. If we go with device feed limiting then we would not have feed pages bookmark able like /feed/pageOne etc.

I don't see a need for book marking feed pages so if you are ok with this let's do it

**Comment by cristidrg** [comment]
@multiojuice @zachtjones @nic-hartley

**Comment by nic-hartley** [comment]
Minor addendum: This will be capped (e.g. at 50). The cap should be easy to modify -- a `final static int`, roughly. It doesn't need to be a property, but that wouldn't hurt anything. A page size greater than the cap will be treated like it was specified to be that cap.
